### ISSUE TITLE
sections have too much empty space

### ISSUE THREAD

**Issue by ln2v** [hackeriet/hackeriet.no#1]
The sections have too much empty space; this creates the impression that there's no more content further down.

![screenshot](https://cloud.githubusercontent.com/assets/697292/10660572/37ecc374-78a8-11e5-90b5-78db2e35ae0e.png)

**Comment by krav** [comment]
Is this for the master branch or capitol's fork?

**Comment by krav** [comment]
Branch, whatever. However this works

**Comment by ln2v** [comment]
Sorry. Capitol's branch.

**Comment by alexanderkjall** [comment]
I added a top level menu and reduced the sections min-height, better?
