### ISSUE TITLE
Blade UID/GID assignment issues.

### ISSUE THREAD

**Issue by stigtsp** [hackeriet/hackeriet.no#23]
uid 1007 shares gid 1007 with uid 1021, etc... Not sure how this happened, but should be fixed.

Example:

This newly created user:
`hackerietweb:x:1024:1010:,,,:/home/hackerietweb:/usr/sbin/nologin`

Shares gid with this old user:
`[redacted]:x:1010:1010:,,,:/home/[redacted]:/bin/bash`

**Comment by Enemico** [comment]
Data has probably been synched from a previous installation, and users / groups have been added manually.

**Comment by stigok** [comment]
There are a lot of these GID/UID issues. Some of which have already been fixed by hand. Nix could potentially be nice for such a shared system.

**Comment by Enemico** [comment]
The machine itself is old, and should be replaced with new hardware that does not use so much electricity. Honestly it does not need to be a NUC, could be something like [this](https://www.ebay.com/itm/Fanless-AES-NI-4-RS232-Dual-Gigabit-2955U-3215U-Core-I3-I5-I7-4th-5th-Box-PC/264492631228?hash=item3d94fd44bc:m:mv_LolTDznU_OKD16v-_e8Q)

**Comment by stigtsp** [comment]
Would be interesting to use NixOps for the shared infra. There is a setup of this here:

https://github.com/hackeriet/nixops/blob/master/common/users.nix

This repo controls 3 virtual machines today:
nux.hackeriet.no
isbit.hackeriet.no
d.hackeriet.no

To get access to all of them, update users.nix and GitHub Actions will rebuild the machines. (There is currently no locking on the actions workflow, so beware).

**Comment by alexanderkjall** [comment]
The machine is already a virtual machine.

Regarding NixOps or what ever: As long as nothing breaks i'm fine with whatever the persons that wants to do something with it does :)

But maybe we should break the different services up into different virtual machines?

**Comment by stigtsp** [comment]
Time passes, this is probably moot.
